### ISSUE TITLE
huggingface_hub.utils._validators.HFValidationError

### ISSUE THREAD

**Issue by xunguangwang** [xirui-li/DrAttack#2]
DrAttack/drattack/utils/model_loader.py", line 105, in get_worker
    tokenizer = AutoTokenizer.from_pretrained(

huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../../../llm_models/vicuna/vicuna-7b-v1.3'. Use `repo_type` argument if needed.

**Comment by xirui-li** [comment]
Would you please check whether you have placed your model at target location?

Please check your configuration [here](https://github.com/xirui-li/DrAttack/blob/main/experiments/configs/template.py) in line 7 and line 10. Make sure this path contains your victim model from huggingface.

**Comment by xunguangwang** [comment]
> Would you please check whether you have placed your model at target location?
> 
> Please check your configuration [here](https://github.com/xirui-li/DrAttack/blob/main/experiments/configs/template.py) in line 7 and line 10. Make sure this path contains your victim model from huggingface.

Thanks very much. That works for me.
