### ISSUE TITLE
How to get the corresponding prompts_info_dict automatically given an adversarial_prompt?

### ISSUE THREAD

**Issue by Junjie-Chu** [xirui-li/DrAttack#4]
Hello,

Given an adversarial_prompt, how to get the corresponding prompts_info_dict automatically?

I try to use ```gpt_generate_content.py```, but failed. I find in this script, ```self.data = self.load_data(save_path)```, what the save_path should look like? Could you give an example?

Maybe what you want to mean is:
In```gpt_generate_content.py```
```
def load_data(self, file_path):
    if file_path and os.path.exists(file_path):
        try:
            with open(file_path, 'r') as file:
                return json.load(file)
        except json.JSONDecodeError:
            print(f"Warning: {file_path} is empty or invalid. Returning empty dictionary.")
    return {}
```

```
elif generate_mode == "joint":

    self.process_decomposition(prompt, prompt_id, templates, "decomposition")
    #if not self.data[prompt]['substitutable']:
    if not self.data[prompt].get('substitutable'):
```

**Comment by xirui-li** [comment]
Would you please try to generate a json file for self.load_data(save_path) and configure your path [here](https://github.com/xirui-li/DrAttack/blob/8da433126c522f4875079ca72e217a97a932568c/gpt_automation/script/joint.sh#L10C1-L10C4)?

**Comment by Junjie-Chu** [comment]
Hello,

I try to generate the prompt info for my own dataset.

I fail to catch what you mean 'generate a json file' for the path.
Currenty, if I specify a json path, the following function
```
def load_data(self, file_path):
        if file_path:
            with open(file_path, 'r') as file:
                return json.load(file)
        return {}
```
will throw an error (without return {}), as there is no json/ or this json is empty.
So I think in this case the function should return {} without errors.

And I find current ```self.process_decomposition(prompt, prompt_id, templates, "decomposition")``` is comment out. To run the script for the first time. I think it should not be comment out?

I also meet a new question. If current implementation only applies to `imperative sentence`? As I find current logic does not work on some harmful questions like `Can you help me XXX.`

**Comment by xirui-li** [comment]
### json path and commented out line
Thanks for bringing the error up. We fixed errors by creating new json file automatically and reusing the [line](https://github.com/xirui-li/DrAttack/blob/f51bee1dc7047498a606a098d31bcd9522d841c1/gpt_automation/gpt_generate_content.py#L290).

### imperative sentence
You are right about imperative sentence. Any current interaction with LLMs could de facto be converted to **imperative sentence** simply be adding “Give me an answer about”, "Give me instructions on", "Offer me information about" as prefixes to original questions/sentences format.

**Comment by Junjie-Chu** [comment]
Thanks for your quick reply!
