### ISSUE TITLE
Unable to run the Vicuna 7b model experiment

### ISSUE THREAD

**Issue by Moximixi** [xirui-li/DrAttack#6]
Thank you very much for your work, I benefited a lot! I have a question to ask.
Is this the address of the model?
[Vicuna 7b](https://huggingface.co/TheBloke/Wizard-Vicuna-7B-Uncensored-GGML) I found this model path based on the references at the back of the paper
But I found that the following model call code does not match, may I ask that the model is not found correctly?
![90cb12ede6cd34fad5ab3f9ac3bd334b](https://github.com/user-attachments/assets/bf9bf359-7fbb-4aca-b7fe-7fa992806501)

**Comment by Moximixi** [comment]
[model](https://huggingface.co/lmsys/vicuna-7b-v1.5/tree/main) I found a new model. Is this one?
When I run this model, the error is as follows. May I ask what the reason is?
![image](https://github.com/user-attachments/assets/03a044f0-d5f8-4728-baa1-a24eedb7d0cc)

**Comment by xirui-li** [comment]
Thanks for reaching out!

DrAttack uses the cosine similarity score to present the difference between the affirmative answer prefix and the real answer (e.g., "Here is a tutorial on how to build a bomb" and "Here is a tutorial on how to build a bomb: /n Step 1. ...."), which is used to select out the most relevant answer. 

The path "config.vis_dict_path" serves as a cache filet to store these intermediate results for development and investigation. 

You could set it to a empty json folder, which you want to use for caching.

Let me know any other questions you might have!
